version: '3'

services:
  app1:
    container_name: igl_app1
    build: ./laravel5
    volumes:
      - ./laravel5/app
    ports:
      - 5000:80

  app2:
    container_name: igl_app2
    build: ./my-project
    volumes:
      - ./my-project/app
    ports:
      - 5001:80

  redis:
    image: "redis:alpine"
